http:
  enabled: false
logger:
  level: OFF

input:
  generate:
    count: 100000000
    batch_size: 10000
    interval:
    mapping: |
      root.text = """Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
        Vivamus faucibus est et metus sodales, vitae faucibus leo faucibus.
        Nunc sed dolor eu erat ullamcorper imperdiet quis in sem. Nullam in
        felis eget enim sollicitudin venenatis. Aliquam erat volutpat.
        Pellentesque vehicula odio ut leo egestas rhoncus. Sed non odio sit
        amet."""

pipeline:
  processors:
    - resource: reverse

output:
  drop: {}
