# metadata.yaml
input:
  file:
    paths: [ ./examples/*.yaml ]
    scanner:
      to_the_end: { }

pipeline:
  processors:
    - python:
        mode: isolated
        script: |
          root.all = metadata()
          root.path = metadata("path")
          meta["junk"] = {"message": "Hello World"}
          meta["name"] = "dave"
    - mapping: |
        root.metadata = metadata()

output:
  stdout: {}

http:
  enabled: false
