# metadata.yaml
input:
  file:
    paths: [ ./examples/*.yaml ]
    scanner:
      to_the_end: { }

pipeline:
  processors:
    - python:
        exe: python3
        script: |
          root.all = metadata()
          root.path = metadata("path")

output:
  stdout: {}
