input:
  python:
    name: df
    serializer: none
    script: |
      import pandas as pd
      df = pd.DataFrame.from_dict({"name": ["Maple", "Moxie"], "age": [8, 3]})

pipeline:
  processors:
    - python:
        script: |
          root = this.to_dict("list")

output:
  stdout: {}

logger:
  level: OFF
http:
  enabled: false
