input:
  python:
    name: pickle_the_time
    batch_size: 5
    serializer: pickle
    script: |
      def pickle_the_time(state = {}):
        import time
      
        cnt = state.get("cnt", 0)
        if cnt > 10:
          # We're done.
          return None
        time.sleep(0.1)
        now = time.ctime()
      
        d = {"now": now, "cnt": cnt}
        state.update({"cnt": cnt + 1})
        return d

pipeline:
  processors:
    - python:
        mode: isolated
        script: |
          import pickle
          from hashlib import sha256

          msg = content()
          d = pickle.loads(msg)
          d.update({"hash": sha256(msg).hexdigest()})

          root = pickle.dumps(d)

output:
  python:
    script: |      
      d = unpickle()
      print(d)

http:
  enabled: false

