# rot13.yaml
input:
  stdin: {}

pipeline:
  processors:
    - python:
        script: |
          import codecs
          msg = content().decode()
          root.original = msg
          root.encoded = codecs.encode(msg, "rot_13")

output:
  stdout: {}

logger:
  level: OFF
http:
  enabled: false
