name: Build without CGO_ENABLED
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5.1.1
      with:
        python-version: "3.12"
        cache: pip

    - name: Install Python setuptools
      run: pip install setuptools

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Build without CGO
      run: CGO_ENABLED=0 go build

    - name: Run Go unit tests
      run: go test -v ./internal/... ./processor/

    - name: Run Python unit tests
      run: python -m unittest discover -v -s processor --pattern "*_test.py"

    - name: Run integration test
      run: ./rp-connect-python test test.yaml
